### ISSUE TITLE
This looks like an interesting start?

### ISSUE THREAD

**Issue by richtong** [ry/tensorflow-resnet#1]
Are there some instructions on how to make it work?

**Comment by maraoz** [comment]
Is this complete or is it a work in progress? I'd like to help, but I'm still learning tensorflow :)

**Comment by richtong** [comment]
I'm the same way. Happy to help!

Thanks,
Rich

Nothing in the world can take the place of persistence... The slogan "press on" has solved and will always solve the problems of the human race. Locomotive Engineers Monthly. November 1914.

http://tongfamily.com | @richtong | http://fb.me/richtong1 | +1-206-963-9029

**Comment by Irtza** [comment]
happy to help, new to TF.

**Comment by ry** [comment]
updated with instructions
