### ISSUE TITLE
a CUDA runtime call was likely performed without using a StreamExecutor context

### ISSUE THREAD

**Issue by ruotianluo** [ry/tensorflow-resnet#22]
I got error like this, which seems to be caused by conflicts between caffe and tensorflow:

current context was not created by the StreamExecutor cuda_driver API: 0x2cc2820; a CUDA runtime call was likely performed without using a StreamExecutor context

However, I didn't find the way to solve it.

**Comment by ruotianluo** [comment]
Solve it by replace the gpu tensorflow with cpu tensorflow

**Comment by xiao1228** [comment]
@ruotianluo Hi I got the same error, but in the code I am using the cpu mode for tensorflow. 
 `with tf.device('/cpu:0'):`
