### ISSUE TITLE
Error restoring the pre-trained resnet models.

### ISSUE THREAD

**Issue by SilviaLauraPintea** [ry/tensorflow-resnet#9]
Hi,

Great job providing the code and the pre-trained resnet models.
However, I have a problem loading/restoring the torrent models.
```python
with tf.Session() as sess:
    dataSaver = tf.train.import_meta_graph('ResNet-L50.meta')
    dataSaver.restore(sess, 'ResNet-L50')
```

I get the error:

> tensorflow.python.framework.errors.DataLossError: Unable to open table file ResNet-L50.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

Any suggestion/help is much appreciated.
Best,
Silvia

**Comment by wenxinxu** [comment]
dataSaver.restore(sess, 'ResNet-L50.ckpt') workd for me

**Comment by SilviaLauraPintea** [comment]
Hi,

Thanks a lot! Indeed, it seems the .ckpt extension is mandatory. 
This tutorial got me a bit confused (https://www.tensorflow.org/versions/r0.9/how_tos/meta_graph/index.html).

Best,
Silvia

**Comment by clever-curl-curl** [comment]
Hi, Silvia
Can you provide a complete file of restoring the model?
